---
abstract: 'Genome Annotation Library'
author:
  - 'Barry Moore <barry.moore@genetics.utah.edu'
build_requires:
  TAP::Harness: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GAL
recommends:
  DBIx::Class::ResultClass::HashRefInflator: 0
  Time::HiRes: 0
requires:
  Bio::DB::Fasta: 0
  Carp: 0
  Cwd: 0
  DBI: 0
  DBIx::Class: 0
  Getopt::Long: 0
  List::MoreUtils: 0
  List::Util: 0
  Module::Build: 0
  Number::Format: 0
  Set::IntSpan::Fast: 0
  Statistics::Descriptive: 0
  Statistics::Descriptive::Discrete: 0
  Text::Graph: 0
  Text::Graph::DataSet: 0
  URI::Escape: 0
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
